<?php
namespace Php247\Translate;

/**
 *
 * @author Clement
 *
 */
Trait FrenchTrait {
    private static $sFrench = [
        'IT Services' => 'Services informatiques',
        'We provide specialized IT services tailored to each user' =>
            'Nous fournissons des services informatiques spécialisés et adaptées à chaque utilisateur',
        'Specialized in standalone applications' => 'Spécialisé dans les applications autonomes',
        'Computer Services' => 'Services Informatiques',
        'Hardware' => 'Matériel Informatique',
        'Embedded systems' => 'Les systèmes embarqués',
        'Training' => 'Formation',
        'Software' => 'Application Informatique',
        'Enterprise' => 'Entreprise',
        'Staff your enterprise with' => 'Farcir votre entreprise avec',
        'Automated billing systems' => 'Systèmes de facturation automatisés',
        'E-mail marketing systems' => 'Mail marketing',
        'Content management' => 'Gestion de contenu',
        'Customer Relationship Management (CRM)' => 'Gestion de la Relation Client (GRC)',
        'Enterprise Resource Planning (ERP)' => 'Progiciels de Gestion Intégré (PGI)',
        'Business Continuity Planning (BCP)' => "Planification de Continuité d'Affaires (PCA)",
        'Financing' => 'Financiers',
        'E-commerce' => 'Commerce électronique',
        'Sell online by' => 'Vente en ligne par',
        'Listing your products' => 'Mettez vos produits en ligne',
        'Payment processing' => 'Traitement de paiement',
        'Consumers pay-per-download basis' => 'Les consommateurs paient-par-téléchargement(CPPT)',
        'Customer profiling' => 'Profilage de client',
        'Product management' => 'Gestion du produit',
        'Newsletters' => "Bulletins d'information",
        'Customer management' => 'Gestion de client',
        'Blogs & Online Diaries' => 'Blogs et journaux intimes en ligne',
        'Post your news by' => 'Diffusez vos nouvelles par',
        'Daily journaling' => 'Journalisation Quotidien',
        'Automated journal' => 'Journal automatisé',
        'Forums' => 'Forums',
        'Build your online group to' => 'créez votre groupe en ligne pour',
        'Share your opinion' => 'Partagez votre avis',
        'Online community' => 'La communauté en ligne',
        'Informational' => 'Informationnel',
        'Share informations by' => 'Partager des informations par',
        'Bring your newspaper online' => 'Apportez votre journal en ligne',
        'Tutorials' => 'Tutoriels',
        'Daily video' => 'Vidéo quotidienne',
        'Social Networking' => 'Réseaux sociaux',
        'Be social by' => 'oyez social par',
        'Publishing yourself to online social network' => 'Publiez-vous au réseau social en ligne',
        'Building application in a online social network' => "Création d'application dans un réseau social en ligne",
        'Personal' => 'Personnel',
        'Share personal information with' => 'Partager des informations personnelles avec',
        'Portofolios' => 'Portofolios',
        'Profile' => 'Profil',
        'Create, manage and maintain your Website includes' => 'Créez, contrôlez et maintenez votre site Web  y inclut',
        'simply, low cost but highest quality' => 'simplement, coût bas mais plus de haute qualité',
        'Responsive design (UI,UX)' => 'Conception sensible (UI,UX)',
        'Development' => 'Développement',
        'Web service & RSS' => 'Service Web, flux RSS et Portlets',
        'SEO integration' => 'SEO ',
        'Api integration (Facebook app, paypal, Twitter)' => 'Api (Facebook app, paypal, Twitter)',
        'Online Marketing' => 'Marketing en ligne',
        'CrossPlatform or Native application' => "CrossPlatform ou l'application native",
        'Gaming' => 'Jeu',
        'Staff your game with' => 'Bourrez votre jeu avec',
        '2D game' => 'jeu 2D',
        '3D game' => 'jeu 3D ',
        'Single user (2D,3D)' => 'un seul joueur (2D,3D)',
        'Multi users (2D,3D)' => 'multi-joueurs (2D,3D)',
        'Lottery game' => 'Jeu de loterie',
        'Directory' => 'Répertoire',
        'By' => 'Par',
        'E-book' => 'Livres en ligne',
        'Search engine' => 'Moteur de recherche',
        'Newspaper' => 'Journal',
        'Place geolocator' => 'Géolocalisateur',
        'Mobile e-commerce' => 'Vente en ligne',
        'Mobile agenda' => 'Agenda',
        'Organise your' => 'Organisez votre',
        'Personal meeting' => 'Rencontre personnelle',
        'Team meeting' => "Réunion d'équipe",
        'Project management' => 'Gestion de projet',
        'Billing' => 'Facturation',
        'Enterprise Application' => "Application d'entreprise",
        'Staff your enterprise mobile application with ' => "Farcir votre entreprise d'applications mobiles avec",
        'Mobile profile' => 'Profil',
        'Create, manage and maintain your mobile application includes' => 'Créez, contrôlez et maintenez votre application mobile inclut',
        'SEM integration' => 'Le marketing avec des moteurs de recherche (MMR)',
        'Api integration (Facebook app, paypal, Twitter,...)' => 'Api(Facebook app, paypal, Twitter,...)',
        'Determining data to be stored' => 'Détermination de données à stocker',
        'Normalization (3rd)' => 'Normalisation (3n)',
        'Determining data type' => 'Détermination du type de données',
        'Entity-Relationship diagram (ERD)' => 'Diagramme entité-relation (DER)',
        'Implementation' => 'Mise en œuvre',
        'With' => 'Avec',
        'Administration' => 'Administration',
        'Develop DBA' => 'développer DBA',
        'Secure' => 'Sécurisé DBA',
        'Maintain' => 'Maintenir DBA',
        'Optimisation' => 'Optimisation',
        'Query processing' => 'Le traitement des requêtes',
        'Query optimisation' => 'Optimisation des requêtes',
        'Create, manage and maintain your database system includes' => ' Créez, contrôlez et maintenez votre système de base de données inclut',
        'Design (3nf)' => 'Conception  (3NF)',
        'Development(SQL, PL/SQL, NoSql)' => 'Développement (SQL, PL/SQL, NoSql)',
        'Migrate' => 'Migrations',
        'Warehouse' => 'Entrepôt',
        'Store and manage your product with' => 'Stocker et gérer votre produit avec',
        'Products registration system' => "Système d'enregistrement de produits",
        'Product accounting' => 'Comptabilité de produit',
        'Enterprice resource management' => "Gestion des ressources d'Enterprice (GES)",
        'Enterprise resource planning (ERP)' => "Planification de ressource d'entreprise (PES)",
        'Create, manage and maintain your desktop application includes' => 'créez, contrôlez et maintenez votre application de bureau inclut',
        'Design (UI, UX)' => 'Conception (UI, UX)',
        'Software Maintenance' => 'Maintenance du logiciel',
        'Updating' => 'Mise à jour',
        'Upgrading' => 'Mise à niveau',
        'Stay safe by' => 'Rester en sécurité par',
        'Backing up your entire website' => "Sauvegarder l'ensemble de votre site internet",
        'Monitor Outages' => 'Surveillez les pannes',
        'Test speed' => 'Examinez le chargement',
        'Link Check' => 'Contrôle de lien',
        'Traffic state' => 'État du trafic',
        'New Features and Upgrades' => 'Nouvelles fonctionnalités et mises à niveau',
        'Application Porting' => "Le portage d'applications",
        'Support for New Devices' => 'Soutien de nouveaux appareils',
        'Enterprise App Store Management, Analytics and Reporting' => "Gestion de magasin d'application d'entreprise, analytique et reportage",
        'Back up' => 'Sauvegarder',
        'Integrity Check' => "Contrôle d'intégrité",
        'Index Optimise' => 'Optimiser les liens',
        'Statistics' => 'Statistiques',
        'Application Migration' => "Migration d'application",
        'Improve customer satisfaction' => 'Améliorer la satisfaction client',
        'Application re-engineering' => "Remachination d'application",
        'manage and maintain your software includes' => 'gérez et maintenez votre logiciel inclut',
        'Change' => 'Modification',
        'Extend' => 'Etendre',
        'simply, low cost but highest quality delivery' => 'simplement, bas prix  mais livraison de plus haute qualité',
        'Interested in' => 'intéressé à',
        'Budget' => 'Budget',
        'Thanks for your order!' => 'Merci pour votre commande!',
        "We'll contact you very soon." => "Nous vous contacterons très bientôt.",
        'Software project' => 'Projet logiciel',
        'project-software' => '<p> Chez <a href="javascript:void()"  dosoft="ds">DoSoft </a>
                            projet, nous traitons votre projet à votre mesure.
                            En ajoutant votre projet, nous travaillons pour vous ,pour finaliser
                            toutes les exigences en fonction de vos besoins et le votre budget défini.
                             </p><p>En outre, lorsque le projet est prêt pour  l’ attaquer, il sera nécessaire
                             de nous assurer les 20% de votre budget du projet qui sera hébergée au ressource de votre projet
                            jusqu’ à  la première livraison de teste.</p>
                            <p>À la livraison nié, et aucune demande modifification, le projet et toute ressource comprend
                  l          hébergé reviennent automatiquement.</p>
                           <p> Pour plus d’informations, s’il vous plaît <a href="#contact" dosoft="contact"> <br/> Contactez-nous </a>ou en savoir plus sur le
                           <a id="ds-faq-project" data-doc="faq" class="faq ds-faq-project" href="javascrip:void()" dosoft="faq"> FAQ. </a>
                          <br/> <strong style="padding: 3px" class="italic pull-right">
                          <a href="javascript:void()"dosoft="ds"> DoSoft </a>
                         <span dosoft = "team">Equipe de projet. </span> </strong></p>',
        'Name'=>'Nom',
        'Company'=>'Nom de société ou particulier',
        'E-mail' => 'Mail',
        'Phone' => 'Numéro de téléphone',
        'Expected start date' => 'Date de début prévue',
        'Expected finish date' => 'Date de finition prévue',
        'Remove' => 'Enlevez',
        'Tell us about your project' => 'Dites-nous au sujet de votre projet',
        'Send request' => 'Envoyez la demande',
        'File' => 'Document',
        'Less than' => 'Moins que',
        'More than' => 'Plus que',
        //Software Activities supported
        'Develop with us your' => 'Développer avec nous votre!',
        'Website' => 'Site internet',
        'Mobile Application' => 'Application pour les portables',
        'Database systems' => 'Systèmes de base de données',
        //(Oracle, MySql,MongoDB)
        'Desktop Application' => 'Logiciel de bureau',
        'Software language' => 'Développement avec Php,Java, C/C++, SqL,NoSQL,Css,Html,JavaScript',
        'Mobile Systems' => 'jQueryMobile, PhoneGap,Android',
        'Maintenance' => 'Maintenance',
        'sources ouvertes' => 'Integration avec Magento, Zend Framework, Wordpress, Facebook api
                                 Google api, Twitter Api...',
        'Submit your project' => 'Soumettez votre projet',
        //Hardware activities
        'Develop and Maintain your hardware with us' => 'Développer avec nous',
        'Design' => 'Conception',
        'Programming' => 'Programmation',
        'Assembly and disassembly' => 'Montage et démontage',
        'Configuration' => 'Configuration',
        //Hardware activities supported
        'Hardware design'=>'Conception de matériel',
        'Architecture'=>'Architecture',
        'Define Overall Chip'=>'Définir ensemble de Chip',
        'Control Model'=>'Modèle de contrôle',
        'Initial Floorplan'=>'Floorplan initiale',
        'Logic'=>'Logique',
        'Behavioral Simulation'=>'Simulation comportementale',
        'Logic Simulation'=>'Simulation du logique ',
        'Synthesis'=>'Synthèse',
        'Datapath Schematics'=>'Schémas de chemin de données',
        'Circuit'=>'Circuit',
        'Cell Libraries'=>'Bibliothèques de cellules',
        'Circuit Schematics'=>'Schémas de  circuit ',
        'Circuit Simulation'=>'Simulation de circuit ',
        'Megacell Blocks'=>'Grand blocs de cellules',
        'Physical'=>'Physique',
        'Layout and Floorplan'=>'Présentation et Floorplan',
        'Place and Route'=>'Lieu et Route',
        'Parasitics Extration'=>'Extration des parasites ',
        'DRC/LVS/ERC'=>'DRC/LVS/ERC',
        'Design and simulate your hardware circuit and chip with tools such as'=>'Conçoit et simule votre circuit de matériel et les puces avec des outils tels que',
        'Hardware circuit maker'=>'Circuit maker',
        'VHDL'=>'VHDL',
        'Verilog'=>'Verilog',
        'Hardware Programming'=>'Programmation matériel',
        'Testing'=>'Test',
        'Declarative'=>'Déclaratif',
        'Constraint'=>'Contrainte',
        'Dataflow'=>'Flux de données',
        'Functional'=>'Fonctionnel',
        'Metaprogramming'=>'Métaprogrammation',
        'Automatic'=>'Automatique',
        'Reflective'=>'Réfléchissant',
        'Homoiconic'=>'Homoiconique',
        'Template'=>'Template',
        'Language-oriented'=>'Langage orienté',
        'Natural language programming'=>'La programmation en langage naturel',
        'Discipline-specific'=>'Particuliers à la discipline',
        'Domain-specific'=>'Spécifique au domaine',
        'Grammar-oriented'=>'Grammaire orientée',
        'Intentional'=>'Intentionnelle',
        'Code your chip with hardware powerful language'=>'Codé votre puce avec un matériel puissant langage',
        'Assembly'=>'Assembleur',
        'Hardware Components'=>'Composants matériel',
        'Disassembly'=>'Démontage',
        'assemble hardware system such as'=>'Montage d’un système matériel comme',
        'Pc Computer (Laptop - Desktop - Mainframe)'=>'Ordinateur PC (ordinateur portable - bureau - Mainframe)',
        'Cell phone'=>'Téléphone cellulaire',
        'All programmable devices'=>'Tous les appareils programmables',
        'disassemble hardware system such as'=>'Démontage d’un système matériel comme',
        'Assembly and disassembly any computer based  devices such as'=>'Montage et Démontage d’un système matériel comme',
        'Laptop'=>'Ordinateur portable',
        'Cell telephone'=>'Cellulaire téléphonique',
        'Desktop computer'=>'Ordinateur de bureau',
        'Cisco switches and routers'=>'Commutateurs et routeurs Cisco',
        'Server'=>'Serveur',
        'for update, upgrade and troubleshoot.'=>'mise à jour, mise à niveau et le dépannage.',
        'Made easy, with low cost but highest quality'=>'Rendu facile, à faible coût, mais la plus haute qualité',
        'Hardware Management'=>'Gestion du matériel informatique',
        'Management'=>'Gestion',
        'configure hardware system such as'=>'configurer le système de matériel tels que',
        'bring any computer based  devices such as'=>'apporter tout appareil basés sur ordinateur tels que',
        'close to your needs'=>'près de vos besoins',
        'Hardware Maintenance'=>'Maintenance de matériel informatique',
        'maintain hardware system such as'=>'maintenir le système de matériel tels que',
        'care of any computer based  devices such as'=>'soins de tout appareil basés sur ordinateur tels que',
        'by resolving any working away'=>'en résolvant toute disfonctionnement',
        'Hardware project'=>'Projet de matériel informatique ',
        'project-hardware'=>'<p> Chez <a href="javascript:void()"  dosoft="ds">DoSoft </a>
                            projet, nous traitons votre projet à votre mesure.
                            En ajoutant votre projet, nous travaillons pour vous ,pour finaliser
                            toutes les exigences en fonction de vos besoins et le votre budget défini.
                             </p><p>En outre, lorsque le projet est prêt pour  l’ attaquer, il sera nécessaire
                             de nous assurer les 20% de votre budget du projet qui sera hébergée au ressource de votre projet
                            jusqu’ à  la première livraison de teste.</p>
                            <p>À la livraison nié, et aucune demande modifification, le projet et toute ressource comprend
                  l          hébergé reviennent automatiquement.</p>
                           <p> Pour plus d’informations, s’il vous plaît <a href="#contact" dosoft="contact"> <br/> Contactez-nous </a>ou en savoir plus sur le
                           <a id="ds-faq-project" data-doc="faq" class="faq ds-faq-project" href="javascrip:void()" dosoft="faq"> FAQ. </a>
                          <br/> <strong style="padding: 3px" class="italic pull-right">
                          <a href="javascript:void()"dosoft="ds"> DoSoft </a>
                         <span dosoft = "team">Equipe de projet. </span> </strong></p>',
        //Hardware software activities
        'Embedded  with us your' => 'Embarqué avec nous votre',
        'Computer Network' => 'Réseau informatique',
        'Robotics & Microcontrollers' => 'Robotique & Microcontrôleurs',
        'Server Management' => 'Gestion du serveur',
        'Industrial automation with PLC' => 'Automatisation industrielle avec CLP',
        'design computer network such as '=>'conception de réseau informatique tel que',
        'Local area network (LAN)'=>'Réseau local (LAN)',
        'Metropolitan area network (MAN)'=>'Réseau métropolitain (MAN)',
        'Wide area network (WAN)'=>'Réseau étendu (WAN)',
        'Wireless network (WN)'=>'Réseau sans fil (WN)',
        'code'=>'codage',
        'Switching'=>'Commutation',
        'Routing'=>'Routage',
        'Virtual network (VLAN, VMAN, VWAN)'=>'Réseau virtuel (VLAN, VMAN, VWAN)',
        'Implementation computer network such as'=>'Mise en œuvre de réseau informatique  tels que',
        'Network performance'=>'Performances du réseau',
        'perform computer network such as'=>'réaliser un réseau informatique tel que',
        'Security'=>'Sécurité',
        'secure computer network such as'=>'sécurisation de réseau informatique tel que',
        'Design, code, maintain and  extend any computer network such as'=>'Conception, codage, maintenir et étendre un réseau informatique tels que',
        'distribution and subnetting'=>'distribution et sous-réseaux',
        'Frame relay network(RIP,..)'=>'Réseau de relais de trame (RIP, ..)',
        'Secure, optimise and Performance'=>'Sécurise, Optimise et Performance',
        'Integration'=>'Intégration',
        'design robotic system'=>'conception d’un système robotique',
        'code robotic system with'=>'Codage système robotique avec',
        'Assembly language'=>'Langage d’assemblage',
        'C language'=>'Langage C',
        'VDCL simulation language'=>'Langage de simulation VDCL',
        'Design, create and extend servo (microcontroller) based robot systems'=>'Conçoit, crée et étend un servo (microcontrôleur) sur la base des systèmes de robots',
        'Single'=>'Unitaire',
        'Distributed'=>'distribué',
        'Installation'=>'Installation',
        'Troubleshooting'=>'Dépannage',
        'File Share'=>'Partage de fichiers',
        'Mail filtering'=>'Filtrage de courrier',
        'Short Message Service (SMS) Gateway'=>'Passage de service de messages courts (SMS)',
        'Install, configure and  extend any file hosting  based on  operating system such as'=>'Installe, configure et étend tout serveur basé sur le système d’exploitation comme',
        'Windows server'=>'Serveur avec Microsoft Windows',
        'Web Server'=>'Serveur Web',
        'File sharing'=>'Partage de fichier',
		'Installation(SMTP,POP/IMAP, Mail filtering)'=>'Installation (SMTP, POP/IMAP, Filtrage du courrier)',
        'best practices'=>'les meilleures pratiques',
        'Design & Integration'=>'Conception et intégration',
        'Ladder Diagrams (LD)'=>'Digramme de Ladder (DL)',
        'Function Block Diagram (FBD)'=>'Logigramme (LOG)',
        'Instruction List (IL)'=>'Liste d’instructions (IL)',
        'Structured Text (ST)'=>'Texte structuré (TS)',
        'Communication network protection'=>'La protection du réseau de communication',
        'tag programmable logic control with SCADA base for design programming any automated production system'=>'contrôle de logique programmable avec la base de la conception SCADA pour la programmation d’un système de production automatisé',
        'Easily, with low cost but highest quality'=>'Facilement, avec un faible coût mais de haute qualité',
        'PLC Maintenance'=>'Entretien PLC',
        'maintain embedded systems such as'=>'Entretien des systèmes embarqués tels que les',
        'Microcontrollers based systems'=>'Systèmes basés sur microcontrôleurs',
        'Servers'=>'Serveurs',
        'Plcs'=>'Plcs',
        'care of any programmable devices by resolving any working away'=>'soin de tous les appareils programmables pour dépannages',
        'Embedded systems project'=>'Projet des systèmes embarqués',
        'Embedded_systems_project'=>'<p> Chez <a href="javascript:void()"  dosoft="ds">DoSoft </a>
                            projet, nous traitons votre projet à votre mesure.
                            En ajoutant votre projet, nous travaillons pour vous ,pour finaliser
                            toutes les exigences en fonction de vos besoins et le votre budget défini.
                             </p><p>En outre, lorsque le projet est prêt pour  l’attaquer, il sera nécessaire
                             de nous assurer les 20% de votre budget du projet qui sera hébergée au ressource de votre projet
                            jusqu’ à  la première livraison de teste.</p>
                            <p>À la livraison nié, et aucune demande modifification, le projet et toute ressource comprend
                  l          hébergé reviennent automatiquement.</p>
                           <p> Pour plus d’informations, s’il vous plaît <a href="#contact" dosoft="contact"> <br/> Contactez-nous </a>ou en savoir plus sur le
                           <a id="ds-faq-project" data-doc="faq" class="faq ds-faq-project" href="javascrip:void()" dosoft="faq"> FAQ. </a>
                          <br/> <strong style="padding: 3px" class="italic pull-right">
                          <a href="javascript:void()"dosoft="ds"> DoSoft </a>
                         <span dosoft = "team">Equipe de projet. </span> </strong></p>',
        //Training
        'Teach yourself' => 'Enseignez-vous',
        'FrondEnd' => "HMTL, CSS, JAVASCRIPT",
        'BACKEND' => "C/C++, JAVA. PHP, SQL, NoSQL",
        'Software Design' => 'Software Design',
        'WEBDESIGH' => 'Responsive Design',
        'Performance' => 'Performance',
        'Sign up' => 'Inscrivez-vous!',
        'About us' => 'à propos',
        'Contact us' => 'Contactez-nous',
        'Presentation and Events'=>'Présentation et Εvénements',
        'Basic'=>'Élémentaire',
        'Professional'=>'Professionnel',
        'Modern'=>'Moderne',
        'you learn and add to your knowledge base the web page presentation in practice with'=>'vous apprenez et ajoutez à votre base de connaissances la présentation de page Web en pratique avec',
        'At'=>'À',
        'high performance'=>'haute performance',
        'Secure coding'=>'Codage sécurisé',
        'in mind. From notice to professional'=>'à l’esprit. D’élémentaire au professionnel',
        'Web and Desktop application'=>'Applications Web et de bureau',
        'you learn and add to your knowledge base the data manipulation languages and saving in practice with'=>'vous apprenez et ajoutez à votre base de connaissances des langages de manipulation et de sauvegarde  de données en pratique',
        'Software technology'=>'Technologie des logiciels',
        'Design lifecycle'=>'Cycle de vie de conception',
        'Requirement gathering'=>'Rassemblement des exigences',
        'Specification export'=>'La définition des spécifications',
        'Analysis phase'=>'Phase d’analyse',
        'Coding'=>'Codage',
        'Maintenance lifecycle'=>'Cycle de vie d’entretien',
        'Handle change request'=>'Gestion de changement',
        'Extend the application'=>'Étendre l’application',
        'User training'=>'Formation des utilisateurs',
        'Howto'=>'Comment',
        'use the application'=>'utiliser l’application',
        'Application Documentation'=>'Documentation de l’application',
        'Application implementation'=>'Mise en oeuvre d’applications',
        'you learn and add to your knowledge base the theory of software technologies used in practice with'=>'vous apprenez et ajoutez à votre base de connaissances de la théorie de technologies logicielles utilisées dans la pratique avec',
        'Methodology'=>'Méthodologie',
        'Design pattern'=>'Modèle de conception',
        'QA (Quality assurance)'=>'AQ (assurance qualité)',
        'Basic project management'=>'La gestion de projet',
        'Responsive Design'=>'Conception adaptée',
        'View'=>'Vue',
        'Content'=>'Contenu',
        'Css based'=>' basé sur CSS',
        'Javascript based'=>'basé sur Javascript',
        'Mixed Css and Javascript'=>'CSS et Javascript mélangés',
        'Content fit'=>'Ajustement de contenu',
        'Content reduce'=>'Le contenu réduit',
        'Content map'=>'contenu mappé',
        'Bandwidth'=>'Bande passante',
        'Connectivity'=>'Connectivité',
        'you learn and add to your knowledge base the interface component fit in practice with'=>'vous apprenez et ajoutez à votre base de connaissances l’ajustement de composant d’interface dans la pratique',
        'Specific device'=>'Spécifique dispositif ',
        'General device'=>'dispositif général',
        'Data mapping (RESTFUL data)'=>'La cartographie des données (données RESTful)',
        'Design optimisation'=>'Optimisation de conception',
        'Code management & Best practices'=>'La gestion de code et meilleures pratiques',
        'Application optimisation'=>'L’optimisation de l’application',
        'you learn and add to your knowledge base the code and data performance  in practice with'=>'vous apprenez et ajoutez à votre base de connaissances de la performance de code et des données dans la pratique',
        'Code optimisation'=>'Optimisation du code',
        'Api consumption'=>'Consommation d’Api',
        'Data reduce and mapping'=>'Réduction et cartographie de données',
        'Code and data structure'=>'Code et structure de données',
        'First name'=>'Prénom',
        'Last name'=>'Nom de famille',
        'Message'=>'Message',
        'Learn Offline'=>'Apprenez off-line',
        'Learn online'=>'Apprenez en ligne',
        'Learn first'=>'Apprentissage d’abord',
        'ds-learn'=>'<p>Apprendre et ajouter à votre base de connaissances,
		               la pratique et la théorie de la technologie de l’informatique 7/7.<br />
                       De logiciel au matériel, de site internet aux applications pour les mobiles.
                       </p><p>Tous nos cours sont week-end et après-midi, tous les jours.<br />
                         À la fin du cours, vous serez tenu de nous payer un certain budget de leçon.
                         </p><p>Pour plus d’informations, s’il vous plaît <a href="#contact"> <br/>Contactez-nous</a>
                          ou lire plus au <a id="ds-faq-project" data-doc="faq" class="faq ds-faq-project" href="javascrip:void()">
                           FAQ.</a><br/><strong style="padding: 3px" class="italic pull-right">
                         <a href="javascript:void()">DoSoft</a> Équipe pédagogique.
                         </strong></p>',
        'Please' => 'Svp',
        'start date' => 'date de début',
        'end date' => 'date de livraison',
        'valid file' => 'fichier valide',
        'Description' => 'description',
        'Online' => 'à distance',
        'Offline' => 'chez moi',
        'Page Not Found (404)'=>'Page introuvable (404)',
        'The page'=>'La page',
        "do not exist." => "n'existe pas.",
        'Please, visit the' => "S'il vous plaît, visitez le",
        'DoSoft informatics services' =>' DoSoft Services informatiques',
        "if you're looking for service" => "si vous êtes à la recherche pour le service",
        ',or'=>',ou',
        "e-mail us"=>"écrivez nous",
        'if you need further assistance.'=>"si vous avez besoin d'aide.",
        'Thank you!'=>'Cordialement!',
        '500 Internal Server Error'=>'Erreur interne du serveur(500)',
        "The server encountered an internal error or misconfiguration and was unable to complete your request"=>"Le serveur a rencontré une erreur interne ou une mauvaise configuration et était incapable de compléter votre demande",
        "Please contact the server administrator and inform them of the time the error occurred, and the actions you performed just before this error"=>"S'il vous plaît contactez l'administrateur du serveur et de les informer du moment où l'erreur a eu lieu, et les actions que vous avez réalisées juste avant cette erreur",
        "More information about this error may be available in the server error log."=>"Plus d'informations sur cette erreur peut être disponible dans le journal des erreurs du serveur.",
        'Apache Server at dosoft.info Port 80'=>'Serveur Apache au dosoft.info Port 80',
        'Please: your e-mail is not valid!'=>"S'il vous plaît: votre mail n'est pas valide!",
        'Please: use other than ours!'=>"S'il vous plaît: utiliser d'autres que la nôtre",
        'Thank you! We will contact back sooner!'=>'Merci! Nous vous contacterons plus tôt!',
        'Thanks for your message'=>'Merci pour votre message',
        "We'll contact you very soon !!!"=>"Nous vous contacterons très bientôt !!!",
        'Please enter the project identifier sent to your E-mail address'=>"S'il vous plaît entrez l'identifiant du projet envoyé à votre adresse mail",
        'Project identifier'=>"L'identifiant du projet",
        "Project identifier <strong>NOT</strong> valid"=>"l'identifiant du projet <strong>NON</strong> valide",
        'Cancel'=>'Annulé',
        'Submit'=>'Soumettre',
        "POLICY_TITLE"=>"Confidentialité",
        "POLICY_P1" =>"Cette déclaration décrit les pratiques de collecte de l'information, l'utilisation et de diffusion applicables à DoSoft services informatiques.",
        "POLICY_P2" =>"Le DoSoft peut utiliser des cookies pour améliorer la fonctionnement de l'application. Si vous ne souhaitez pas recevoir de cookies, vous pouvez modifier les paramètres de votre navigateur enfin de leur refuser. S'il vous plaît noter que si vous choisissez de refuser les cookies,cela peut limiter l'accès à certaines zones de l'application et avoir un effet négatif sur la performance.",
        "POLICY_P3" =>"Les informations non personnelles sont collectées par les services de l'informatique DoSoft.",
        "POLICY_P4" =>"DoSoft services informatiques recueille certaines informations non personnelles. Cela inclut les données relatives à la durée de la visite de l'utilisateur, à quelle fréquence ils sont accessibles et d'autres informations relatives à l'activité. Cette information est utilisée pour analyser l'utilisation de l'application, pour améliorer et renforcer la qualité de nos services. Cette information est toujours sous la forme d'informations agrégées, non personnelles. Cette information peut être partagée avec les partenaires de DoSoft services informatiques afin de fournir les meilleurs services pour vous.",
        "POLICY_P5" =>"Adresse IP de chaque utilisateur est également recueillis par le serveur web de DoSoft.info. Ceux-ci est perçus au titre des données agrégées non personnelles. Il est recueilli pour nous aider à diagnostiquer les problèmes avec nos informatique services. DoSoft services informatiques peuvent utiliser des tiers pour analyser des informations non-personnelles collectées par nous. Cela peut également être mis à la disposition des organisations de médias et les sociétés de recherche à des fins de comparaison.",
        "POLICY_P6" =>"Les renseignements personnels recueillis par DoSoft services informatiques pour les recherches et la navigation de contenu sur notre application peut être consulté lors de l'enregistrement de service. Si vous choisissez d'ajouter votre service au DoSoft.info, nous allons recueillir des renseignements personnels au sujet de vos nom et coordonnées. Cette information peut être consultée par vous en nous contactant.",
        "POLICY_P7" =>"Cette information est utilisée uniquement pour faciliter notre collaboration future. Vous pouvez modifier la demande de supprimer les informations de votre compte. Toute information peut être supprimé retenu sur DoSoft les systèmes informatiques des services pour une période de temps après. DoSoft services informatiques se réserve un pouvoir discrétionnaire pour désactiver ou supprimer des comptes à tout moment.",
        "POLICY_PERSONAL_INFO_TITLE" =>"Publication des infomations personnels",
        "POLICY_PERSONAL_INFO_P" =>"DoSoft services informatiques a des zones accessibles au public de l'application, par exemple les blogs. Nous vous suggérons fortement de ne pas publier des informations personnelles dans ces zones. DoSoft services informatiques prend aucune responsabilité pour toute collecte ou l'utilisation par des tiers des informations contenues dans ce chemin.",
        "POLICY_PERSONAL_SECURITY_TITLE" =>"Sécurité et confidentialité",
        "POLICY_PERSONAL_SECURITY_P" =>"DoSoft services informatiques prend toutes les mesures raisonnables pour assurer la protection de vos informations et la sécurité de notre système. Nos membres de l'équipe sont également tenus de respecter la confidentialité de vos informations personnelles.",
        "POLICY_PERSONAL_SECURITY_P_1" =>"Cependant, nous ne pouvons pas garantir la sécurité de ces informations et nous ne sommes pas responsables de tout accès non autorisé à vos informations personnels." ,
        "POLICY_PERSONAL_SECURITY_P_2" =>"l est également important que vous gardiez vos coordonnées confidentielles, y compris votre identifiant de service. Si vous soupçonnez tout accès non autorisé ou de l'utilisation de votre identifiant de service, ou de toute autre violation de sécurité s'il vous plaît nous en informer immédiatement." ,
        "POLICY_PERSONAL_OVERSEAS_TITLE" =>"L'accès à vos informations" ,
        "POLICY_PERSONAL_OVERSEAS_P" =>"DoSoft Services informatiques peut de temps en temps revoir les informations de votre service. Vous vous engagez lorsque vous nous fournissez vos informations de service." ,
        "POLICY_PERSONAL_ACCESS_TITLE" =>"Comment accéder à vos informations" ,
        "POLICY_PERSONAL_ACCESS_P" =>"Si vous êtes un utilisateur enregistré, vous pouvez accéder à vos informations via votre e-mail. Cette information peut être modifié et supprimé." ,
        "POLICY_CHANGE_TITLE" =>"Changements" ,
        "POLICY_CHANGE_P" =>"DoSoft Services informatiques peut de temps en temps à décider de changer cette politique. Toutes les versions mises à jour seront disponibles sur l'application." ,
        "POLICY_CONTACT_US_TITLE" =>"Contactez nous" ,
        "POLICY_CONTACT_US_P" =>"Si vous avez des questions concernant cette politique ou l'utilisation de vos informations s'il vous plaît contactez-nous" ,
        "FAQ_HOW_IT_WORKS_TITLE" =>"Comment ça marche ?" ,
        "FAQ_HOW_IT_WORKS_P" =>"DoSoft Services informatiques  a catégorisé ses services pour vous aider à trouver facilement la catégorie de votre service. Pour ajouter votre service, vous devez remplir le formulaire des informations de votre service. Toutes vos informations seront envoyées à vous dans votre adresse mail et conservé aussi dans notre  système informatique. Chaque service possède un identifiant unique qui est envoyé dès le premier contact. DoSoft Services informatiques  vous contactera ensuite pour la vérification.",
        "FAQ_WHAT_SERVICE_TITLE" =>"Type de service",
        "FAQ_WHAT_SERVICE_P" =>"DoSoft services informatiques gère le projet logiciel et matériel pour leur conception, développement, intégration, la mise en œuvre et la documentation. Aussi, offre une formation informatique du débutant au professionnels." ,
        "FAQ_SERVICE_ADD_TITLE" =>"Comment ajouter mon service ?" ,
        "FAQ_SERVICE_ADD_P" =>"Il suffit de cliquer sur votre catégorie de service et de remplir dans le formulaire les informations de votre service." ,
        "FAQ_SERVICE_PAY_TITLE" =>"Comment payer pour mon service?" ,
        "FAQ_SERVICE_PAY_P" =>"DoSoft services informatiques accepte tous les types de paiement, y compris PayPal et virement bancaire." ,
        "FAQ_SERVICE_CHANGE_DETAIL_TITLE" =>"Que faire si je dois changer les détails de mon service que je l'ai déjà en cours?" ,
        "FAQ_SERVICE_CHANGE_DETAIL_P" =>"Pas de problème. Toute modification peut être fourni sur un service en cours. Selon le type de changement, gardez à l'esprit que, DoSoft services informatique examinera avec vous la date de livreson et le coût." ,
        "FAQ_SERVICE_NO_MORE_INFO_TITLE" =>"Que faire si je ne donne pas plus d'informations ?" ,
        "FAQ_SERVICE_NO_MORE_INFO_P" =>"Pas de problème. Plus de détail, après un contact avec DoSoft services informatiques." ,
        "FAQ_SERVICE_MORE_INFO_TITLE" =>"Que faire si le développeur ou le formateur demande plus de détails au sujet de mon service ?" ,
        "FAQ_SERVICE_MORE_INFO_P" =>"Pas de problèmes, DoSoft services informatiques  pose des questions pour clarifier votre service." ,
        "FAQ_SERVICE_ENSURED_TITLE" =>"Mon service est-il assuré ?" ,
        "FAQ_SERVICE_ENSURED_P" =>"Oui, DoSoft services informatiques travaille en étroite collaboration avec vous." ,
        "FAQ_SERVICE_CONTACT_DEV_TRNER_TITLE" =>"Je peut contacter un développeur ou formateur par téléphone ou par mail ?" ,
        "FAQ_SERVICE_CONTACT_DEV_TRNER_P" =>"Oui, DoSoft services informatiques travaille en étroite collaboration avec vous." ,
        "FAQ_SERVICE_IN_PROCESS_MORE_INFO_TITLE" =>"Que faire si je possède plus qu'une  service en processus?" ,
        "FAQ_SERVICE_IN_PROCESS_MORE_INFO_P" =>"DoSoft services informatiques suit votre service selon les dates fourni par vous." ,
        "FAQ_SERVICE_DEV_TRUSTABLE_TITLE" =>"Comment puis-je savoir si le développeur ou le formateur est digne de confiance ou non?" ,
        "FAQ_SERVICE_DEV_TRUSTABLE_P" =>"Tous nos gens sont dignes de confiance, membre d'une équipe dans la discipline spécifique." ,
        "FAQ_SERVICE_DEV_CHOOSE_TITLE" =>"Je peux choisir un développeur ou un formateur ?" ,
        "FAQ_SERVICE_DEV_CHOOSE_P" =>"Non" ,
        "FAQ_SERVICE_GET_READY_TITLE" =>"Combien de temps cela prend-il pour livré mon service ?",
        "FAQ_SERVICE_GET_READY_P" =>"DoSoft services informatiques respecte votre date initiale de démarrage et de la livraison du service. Toute votre modification sur un service en processus peuvent entraîner l'augmentation du date de livraison. ",

    ];
    private static $sallFrench = array(
        'Services' => array(),
        'Software' => array(),
        'Hardware' => array(
            ''
        ),
    );

    public static function getFrench(){
        return self::$sFrench;
    }

    public static function getAlltranslated($holder)
    {
        return self::$sallFrench[$holder];
    }
}